In [1]:
import pandas as pd
import numpy as np
data = [15, 21, 29, 21, 15, 24, 32, 21, 15, 30]
df = pd.DataFrame(data, columns=["Values"])
print("Mean of data:",df["Values"].mean())
print("Median of data:",df["Values"].median())
print("Mode of data:",df["Values"].mode())
print("Standard deviation of data:",df["Values"].std())
print("Variance of data:",df["Values"].var())

Mean of data: 22.3
Median of data: 21.0
Mode of data: 0    15
1    21
Name: Values, dtype: int64
Standard deviation of data: 6.3779132776934
Variance of data: 40.67777777777778


In [4]:
import numpy as np
import pandas as pd
df = pd.read_csv("robot_dataset(robot_dataset)_1 (1).csv")
print("Mean Accuracy:", df["Accuracy (%)"].mean())
print("Total Robots:", df["Robot_ID"].count())
print(df[["Robot_ID", "Task_Type"]])
print(df.iloc[10:20])
print(df.groupby(['Sensor_Type']).mean(numeric_only=True))
grouping = df.groupby(['Task_Type','Environmental_Status'])
print(grouping.first())

Mean Accuracy: 94.92060000000001
Total Robots: 500
    Robot_ID   Task_Type
0    RBT_001  Inspection
1    RBT_002    Assembly
2    RBT_003  Inspection
3    RBT_004     Welding
4    RBT_005    Assembly
..       ...         ...
495  RBT_496  Inspection
496  RBT_497  Inspection
497  RBT_498  Inspection
498  RBT_499    Assembly
499  RBT_500    Assembly

[500 rows x 2 columns]
   Robot_ID   Task_Type Component_ID     Sensor_Type            Sensor_Data  \
10  RBT_011    Assembly      CMP_567          Camera        0 (no obstacle)   
11  RBT_012    Painting      CMP_268           LIDAR              75.8 (°C)   
12  RBT_013  Inspection      CMP_631         Thermal      98% (defect-free)   
13  RBT_014  Inspection      CMP_115          Camera              82.4 (°C)   
14  RBT_015  Inspection      CMP_932  LIDAR + Camera       92% (visual fit)   
15  RBT_016    Assembly      CMP_424  LIDAR + Camera       92% (visual fit)   
16  RBT_017  Inspection      CMP_201          Camera        0 (no obstac

In [5]:
name = "Keerthana"
age = 20
height = 5.5
is_student = True
print(f"My name is {name}. I am {age} years old.")
print(f"My height is {height} feet.")
print(f"Am I a student? {is_student}.")

My name is Keerthana. I am 20 years old.
My height is 5.5 feet.
Am I a student? True.


In [6]:
num = int(input("Enter an integer:"))
if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

Enter an integer: -4


The number is negative.


In [7]:
num = int(input("Enter a number: "))
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

Enter a number:  5


5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [8]:
fruits = ["Apple", "Banana", "Cherry", "Mango", "Orange"]
fruits.append("Grapes")
print("After adding Grapes:", fruits)
fruits.remove("Banana")
print("After removing Banana:", fruits)
fruits.sort()
print("After sorting:", fruits)
fruits.reverse()
print("After reversing:", fruits)
index_cherry = fruits.index("Cherry")
print("Index of Cherry:", index_cherry)
third_fruit = fruits[2]
print("The third fruit in the list:", third_fruit)
sliced_fruits = fruits[1:4]
print("Sliced list (index 1 to 3):", sliced_fruits)

After adding Grapes: ['Apple', 'Banana', 'Cherry', 'Mango', 'Orange', 'Grapes']
After removing Banana: ['Apple', 'Cherry', 'Mango', 'Orange', 'Grapes']
After sorting: ['Apple', 'Cherry', 'Grapes', 'Mango', 'Orange']
After reversing: ['Orange', 'Mango', 'Grapes', 'Cherry', 'Apple']
Index of Cherry: 3
The third fruit in the list: Grapes
Sliced list (index 1 to 3): ['Mango', 'Grapes', 'Cherry']


In [9]:
numbers = (10, 20, 30, 40, 50)
print("Third element:", numbers[2])
print("Sliced tuple (1 to 3):", numbers[1:4])
print("Index of 30:", numbers.index(30))
print("Count of 20:", numbers.count(20))
print("Sum:", sum(numbers))
print("Max:", max(numbers), "Min:", min(numbers))

Third element: 30
Sliced tuple (1 to 3): (20, 30, 40)
Index of 30: 2
Count of 20: 1
Sum: 150
Max: 50 Min: 10


In [10]:
students = {"Keerthana": 85, "Bavya": 92, "Lowkya": 78}
students["Keerthana"] = 88
students["Bavya"] = 90
students.pop("Lowkya")
print("Keerthana's Marks:", students["Keerthana"])
print("Final Marks:", students)

Keerthana's Marks: 88
Final Marks: {'Keerthana': 88, 'Bavya': 90}


In [11]:
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
print("Union:", set1 | set2)
print("Intersection:", set1 & set2)
print("Difference (set1 - set2):", set1 - set2)
print("Symmetric Difference:", set1 ^ set2)

Union: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection: {4, 5}
Difference (set1 - set2): {1, 2, 3}
Symmetric Difference: {1, 2, 3, 6, 7, 8}


In [12]:
def find_largest(numbers):
    return max(numbers)
list = [12, 45, 23, 67, 89, 34]
largest_number = find_largest(list)
print("The largest number in the list is:", largest_number)

The largest number in the list is: 89


In [13]:
squares_of_even_numbers = [x**2 for x in range(1, 21) if x % 2 == 0]
print(squares_of_even_numbers)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [15]:
# Taking two numbers as input from the user
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
product = (lambda x, y: x * y)(num1, num2)
print("The product of", num1, "and", num2, "is:", product)

Enter the first number:  45
Enter the second number:  32


The product of 45.0 and 32.0 is: 1440.0


In [1]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print("One-dimensional array:")
print("Array:", arr_1d)
print("Shape:", arr_1d.shape)
print("Dimensions:", arr_1d.ndim)
print()
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Two-dimensional array:")
print("Array:", arr_2d)
print("Shape:", arr_2d.shape)
print("Dimensions:", arr_2d.ndim)
print()
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Three-dimensional array:")
print("Array:", arr_3d)
print("Shape:", arr_3d.shape)
print("Dimensions:", arr_3d.ndim)

One-dimensional array:
Array: [1 2 3 4 5]
Shape: (5,)
Dimensions: 1

Two-dimensional array:
Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2

Three-dimensional array:
Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3


In [2]:
import numpy as np
arr = np.random.random((5, 5)) * 100 
arr = arr.astype(int)
print("5x5 Array:\n", arr)
print("\nElement at (2, 3):", arr[1, 2])  # Second row, third column
print("Second row:", arr[1])
print("Third column:", arr[:, 2])
print("Last row:", arr[4])
print("Bottom-right element:", arr[4, 4])

5x5 Array:
 [[ 4 68 52 38 56]
 [34 72 34 98  7]
 [ 3 64  4  7  4]
 [80 67 56 31  8]
 [83 22 14 95 72]]

Element at (2, 3): 34
Second row: [34 72 34 98  7]
Third column: [52 34  4 56 14]
Last row: [83 22 14 95 72]
Bottom-right element: 72


In [3]:
import numpy as np
arr = np.arange(1, 17).reshape(4, 4)
print("4x4 Array:\n", arr)
print("\nFirst two rows:\n", arr[:2])
print("\nLast two columns:\n", arr[:, -2:])
print("\nDiagonal elements:", arr.diagonal())
print("\nSubarray (2nd and 3rd rows, 2nd and 3rd columns):\n", arr[1:3, 1:3])

4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First two rows:
 [[1 2 3 4]
 [5 6 7 8]]

Last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

Diagonal elements: [ 1  6 11 16]

Subarray (2nd and 3rd rows, 2nd and 3rd columns):
 [[ 6  7]
 [10 11]]


In [4]:
import numpy as np
arr_2d = np.arange(1, 13).reshape(6, 2)
print("2D Array (6, 2):\n", arr_2d)
arr_3d = arr_2d.reshape(2, 3, 2)
print("\nReshaped 3D Array (2, 3, 2):\n", arr_3d)
arr_flattened = arr_3d.flatten()
print("\nFlattened Array:\n", arr_flattened)

2D Array (6, 2):
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Reshaped 3D Array (2, 3, 2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Flattened Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_1d = np.array([10, 20, 30])
result = arr_2d + arr_1d
print("Result after Broadcasting:\n", result)

Result after Broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [6]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print("Addition:\n", A + B)
print("\nSubtraction:\n", A - B)
print("\nMultiplication:\n", A * B)
print("\nDivision:\n", A / B)

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Division:
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [7]:
import pandas as pd
data = {'Name': ['Keerthana', 'Bavya', 'Lowkya'],
        'Mathematics': [85, 90, 78],
        'AI': [88, 76, 92],
        'Chemistry': [79, 84, 85]}
df = pd.DataFrame(data)
df['Total'] = df[['Mathematics', 'AI', 'Chemistry']].sum(axis=1)
df['Grade'] = df['Total'].apply(lambda x: 'A' if x >= 240 else 'B' if x >= 180 else 'C' if x >= 120 else 'D')
print(df)

        Name  Mathematics  AI  Chemistry  Total Grade
0  Keerthana           85  88         79    252     A
1      Bavya           90  76         84    250     A
2     Lowkya           78  92         85    255     A
